#!/bin/bash

sudo systemctl enable client_akku.service
sudo systemctl enable client_lights.service

sudo systemctl start client_akku.service
sudo systemctl start client_lights.service

sudo mv /etc/dhcpcd_tmp/dhcpcd.conf /etc/dhcpcd.conf
