#!/bin/bash

sudo systemctl enable service_akku.service
sudo systemctl enable service_lights.service

sudo systemctl start service_akku.service
sudo systemctl start service_lights.service

sudo mv /etc/dhcpcd_tmp/dhcpcd.conf /etc/dhcpcd.conf
